### PR TITLE
Remove docs build products that were accidentally committed

### PR DESCRIPTION
**Pull request by lpsinger**

### CODE REVIEW

**Comment by farr** [comment]
Hi Leo.  Those aren't accidentally committed; they are intentionally left in the repo so that people have the docs when they download.  Do they really cause a problem, or are you just trimming as much as possible?

**Comment by lpsinger** [comment]
The js files generate some debian packaging warnings, though nothing significant. A better solution would be to nuke those files but enable [Read The Docs](http://docs.readthedocs.io/en/latest/webhooks.html#github) and add a link to your README.

**Comment by farr** [comment]
Moved to readthedocs, and nuked these files in bae8a27dcba4059361b41677778c2585b95f88db .

**Comment by lpsinger** [comment]
Wow that was fast! That's all I had for today. Thanks!

**Comment by farr** [comment]
No problem.  Thanks for curating the Debian package and the v0.2 release.

**Pull request closed without merging**
