### PR TITLE
Read samples using lalinference.io.hdf5.read_samples

### PR DESCRIPTION
**Pull request by lpsinger**
This tracks a new addition to the LALInference API.

### CODE REVIEW

**Comment by farr** [comment]
Hi Leo,

I can check, but maybe you know already: does using hdf5.read_samples mean that we can no longer read the old-style posterior samples files (header line with column names in ASCII, followed by posterior samples, one per row)?  

Will

**Comment by lpsinger** [comment]
> does using hdf5.read_samples mean that we can no longer read the old-style posterior samples files (header line with column names in ASCII, followed by posterior samples, one per row)?

Correct.

**Comment by farr** [comment]
Ok.  Then could you modify the patch so that it tries to hdf5.read_samples,
and if that fails tries to read the old-style text files
(np.genfromtxt(..., names=True))?  We should support the old-style files
for at least one more observing run, I think....

**Comment by lpsinger** [comment]
> Ok.  Then could you modify the patch so that it tries to hdf5.read_samples, and if that fails tries to read the old-style text files (np.genfromtxt(..., names=True))?  We should support the old-style files for at least one more observing run, I think....

Done.

**Comment by farr** [comment]
...and merged onto master at GitHub.

Thanks, Leo!

Will

**Pull request merged**
