### PR TITLE
Restructure class hierarchy to add Python multiprocessing

### PR DESCRIPTION
**Pull request by lpsinger**
Multiprocessing is used during the two most CPU-intensive steps: the search over the number of clusters and extracting the distance moments. This makes the code WAY faster on big, multi-core machines. This will be important for rapidly generating results for low- or medium-latency parameter estimation analyses.

Note that plotting the KDE assignments was removed as collateral damage in making this change.

### CODE REVIEW

**Comment by lpsinger** [comment]
Hang on, this needs a little more work.

**Comment by farr** [comment]
@lpsinger Yeah, I checked out the version after the first commit, and seem to be getting strange errors about latitudes out of range:

```
ValueError: Latitude angle(s) must be within -90 deg <= angle <= 90 deg, got [ 7451.37396385  7451.37396385  4230.11124738 ...,  5017.17311386
  5747.06356216  8173.35166776] deg
```

on a test with GW150914 posterior samples.  

Is it now in a state that I can test it?

**Comment by lpsinger** [comment]
No, but I am finding a very perplexing error and could use some help tracking it down. Are you free to talk on Skype?

**Comment by lpsinger** [comment]
You were spot on (over Skype) that the issue was that `astropy.utils.console.ProgressBar.map(..., multiprocess=True)` returns results out of order. I'm now getting sane sky maps. I've started the review jobs now. I'll let you know when they are done.

**Comment by farr** [comment]
@lpsinger I just had a look with my (much less extensive) local tests, and this PR seems to be fine.  Let me know when the review jobs finish, and I'll merge it in (assuming there are no more surprises).

**Comment by lpsinger** [comment]
> @lpsinger I just had a look with my (much less extensive) local tests, and this PR seems to be fine. Let me know when the review jobs finish, and I'll merge it in (assuming there are no more surprises).

Still running...

**Comment by lpsinger** [comment]
> You were spot on (over Skype) that the issue was that astropy.utils.console.ProgressBar.map(..., multiprocess=True) returns results out of order. I'm now getting sane sky maps. I've started the review jobs now. I'll let you know when they are done.

I've offered a fix upstream to Astropy: astropy/astropy#6439.

**Pull request merged**
